In [2]:
import numpy as np

In [3]:
np.random.random()

0.03426444541984286

In [4]:
np.random.random(5)

array([0.10448996, 0.51352473, 0.18805215, 0.79724973, 0.16428718])

In [5]:
np.random.randint(9)

5

In [6]:
np.random.random((2,4,7))

array([[[0.73597552, 0.61486008, 0.25254064, 0.11136052, 0.84033105,
         0.44597549, 0.18883428],
        [0.32287836, 0.03202121, 0.79309444, 0.02499434, 0.05566666,
         0.52723374, 0.37590128],
        [0.88340541, 0.74700777, 0.28954714, 0.78654794, 0.36821625,
         0.90544769, 0.99847924],
        [0.55189649, 0.62678729, 0.42722316, 0.69569356, 0.43675711,
         0.43764378, 0.15312893]],

       [[0.02123979, 0.76201438, 0.97585034, 0.62756874, 0.33036687,
         0.78788732, 0.10516314],
        [0.51975768, 0.62658973, 0.78850774, 0.43876051, 0.64916111,
         0.53080763, 0.93276672],
        [0.04789704, 0.15325171, 0.62272873, 0.37094268, 0.66437742,
         0.84308589, 0.36214643],
        [0.22513392, 0.95882943, 0.18033043, 0.42640679, 0.9173223 ,
         0.19905886, 0.40469755]]])

# 2. Randint Function

.It generates random interger(s) number between the given range

By default the range will start from 0

The numbers can repeat

In [7]:
np.random.randint(2,13)

2

In [8]:
np.random.randint(2,13,6) # Repeat the number below is "12"

array([ 2,  3,  3,  4,  2, 11])

# 3. Rand Function

It returns random float number between 0 and 1

In [9]:
np.random.rand()

0.8975042104987216

In [10]:
np.random.rand(2,5)

array([[0.57142643, 0.5732836 , 0.98371084, 0.48624602, 0.83394054],
       [0.44041498, 0.10295399, 0.5273788 , 0.58633961, 0.66821408]])

In [11]:
np.random.rand(1,3,5)

array([[[0.50845645, 0.66380184, 0.60544148, 0.15971411, 0.12636616],
        [0.57859412, 0.47064062, 0.06348085, 0.72962523, 0.33066484],
        [0.87830486, 0.28991379, 0.55711646, 0.28118957, 0.55348546]]])

# 4. Randn Function (Show the -ve value in array)

In [12]:
np.random.randn()

-0.30435143807736326

In [13]:
np.random.randn(2,6)

array([[-0.39282111, -0.68097444,  0.13750123,  0.10121271,  0.82994635,
         2.03231477],
       [-0.57845099, -0.26386649,  0.0861015 ,  0.75548047,  1.77960408,
         0.27746267]])

# 5. Uniform Function 

It returns random float number between the given range of values 


The random numbers can't repeat


By default the numbers starts from o


If nothing is passed in (), it will return a float number between 0 and 1

In [14]:
np.random.uniform(2,5)

3.345725167592574

In [15]:
np.random.uniform(2,6,9)

array([4.19882488, 5.30630393, 4.63094012, 4.6058152 , 2.53906712,
       2.6084188 , 2.3305894 , 4.21449497, 3.24251447])

In [16]:
np.random.uniform(9)

4.7123861029567635

In [17]:
np.random.uniform()

0.5822295302350529

# 6.Choice Function

It returns random integers number from the given sequence


The range starts from 0 by default

If only 1 element is passed, then it will return a number between 0 and that element

By default replace=True, which means that the numbers can repeat

In [18]:
np.random.choice([12,14,99,15,87,54,65,874
                 ])

874

In [19]:
np.random.choice([11,15,20,25,30,35],5)

array([35, 25, 30, 20, 30])

In [20]:
np.random.choice(13,350)

array([ 3,  1,  1,  1,  4,  8, 11, 12,  6, 12, 10,  3, 12,  6,  0,  2,  5,
        1, 11,  3, 12,  2,  6,  9,  2,  3,  9,  1, 10,  7,  7,  7,  2,  4,
        2,  1,  7,  9, 12,  8,  2,  3,  6,  6,  0,  6,  3,  8,  4,  4,  0,
        7,  6, 12,  1,  8, 10,  4,  9,  7,  8,  8,  7,  7,  0,  5,  0,  7,
       12,  8,  4,  7,  9, 12, 11,  9,  2,  2,  4,  0,  0, 10, 11,  6,  2,
        8,  1,  8,  3,  5,  3,  1,  1, 12,  0,  2,  5,  6,  9,  1,  5,  9,
        7,  7,  8, 10,  4,  5,  3,  4,  5,  6,  7,  4,  6,  0,  3,  8,  1,
        7,  1,  7,  4, 11,  1,  0,  5, 11,  8, 11, 10,  8,  4, 11, 12,  1,
       12,  8, 12,  9, 11,  8,  2,  0,  6, 11,  7, 11,  7,  2, 10, 10,  9,
        3, 10,  9,  4,  6, 11, 10,  8, 11, 10,  5,  1,  8,  2, 11,  4,  4,
        2,  6,  5,  1,  7, 12,  2,  3, 11,  5, 10,  2,  6,  9,  2,  5,  3,
        6, 11, 10,  6, 11,  5,  4,  0,  0,  4, 12,  4,  1, 12,  2,  4,  2,
        4,  9, 10,  3,  5,  0,  3,  9,  3,  4,  8,  3,  3,  1,  4, 12,  9,
        2,  2,  3,  5,  1

In [21]:
np.random.choice(12)

10

In [22]:
np.random.choice([12,16,18,19,20,26,29], size=20, replace=True)

array([20, 12, 20, 18, 26, 26, 20, 26, 12, 12, 29, 19, 16, 19, 19, 19, 16,
       12, 20, 16])

# 9. Random Function

Linspace function returns evenly (linearly) space values within a given iterval

np.linspace(start_value,stop_value,num=50,endpoint=False,retstep=True,dtype=None)

Note-By default it shows 50 values

In [23]:
import numpy as np

In [24]:
a=np.linspace(2,30,num=15)

In [25]:
print(a)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30.]


In [30]:
a=np.linspace(2,20,num=13,endpoint=True)
print(a)

[ 2.   3.5  5.   6.5  8.   9.5 11.  12.5 14.  15.5 17.  18.5 20. ]


In [33]:
a=np.linspace(2,20,num=10,endpoint=True)

In [34]:
print(a)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [37]:
a=np.linspace(2,20,num=10,endpoint=True, retstep=True)

In [38]:
print(a)

(array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.]), 2.0)


In [39]:
a=np.linspace(2,20,num=10,endpoint=True, retstep=False)
print(a)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [40]:
a=np.linspace(2,20,num=10,endpoint=True, retstep=False, dtype=str)
print(a)

['2.0' '4.0' '6.0' '8.0' '10.0' '12.0' '14.0' '16.0' '18.0' '20.0']


In [41]:
a=np.linspace(2,20)
print(a)

[ 2.          2.36734694  2.73469388  3.10204082  3.46938776  3.83673469
  4.20408163  4.57142857  4.93877551  5.30612245  5.67346939  6.04081633
  6.40816327  6.7755102   7.14285714  7.51020408  7.87755102  8.24489796
  8.6122449   8.97959184  9.34693878  9.71428571 10.08163265 10.44897959
 10.81632653 11.18367347 11.55102041 11.91836735 12.28571429 12.65306122
 13.02040816 13.3877551  13.75510204 14.12244898 14.48979592 14.85714286
 15.2244898  15.59183673 15.95918367 16.32653061 16.69387755 17.06122449
 17.42857143 17.79591837 18.16326531 18.53061224 18.89795918 19.26530612
 19.63265306 20.        ]


In [44]:
a=np.linspace(1,3)
print(a)           # by default it show the value is "50"

[1.         1.04081633 1.08163265 1.12244898 1.16326531 1.20408163
 1.24489796 1.28571429 1.32653061 1.36734694 1.40816327 1.44897959
 1.48979592 1.53061224 1.57142857 1.6122449  1.65306122 1.69387755
 1.73469388 1.7755102  1.81632653 1.85714286 1.89795918 1.93877551
 1.97959184 2.02040816 2.06122449 2.10204082 2.14285714 2.18367347
 2.2244898  2.26530612 2.30612245 2.34693878 2.3877551  2.42857143
 2.46938776 2.51020408 2.55102041 2.59183673 2.63265306 2.67346939
 2.71428571 2.75510204 2.79591837 2.83673469 2.87755102 2.91836735
 2.95918367 3.        ]


In [45]:
a=np.linspace(1,3,num=12)
print(a)            # It show the "12" values as per num=12

[1.         1.18181818 1.36363636 1.54545455 1.72727273 1.90909091
 2.09090909 2.27272727 2.45454545 2.63636364 2.81818182 3.        ]


# Empty Funcion is used to creat an array of arbitary values, of given shape and datatype, without initializing the entries.

Syntax: np.empty(shape,dtype)

shape can given a list or tuple form

The default data type is float

In [50]:
import numpy as np                                                                     # importing the numpy library

In [53]:
a=np.empty(7)


In [54]:
print(a)

[7.74860419e-304 7.74860419e-304 7.74860419e-304 7.74860419e-304
 7.74860419e-304 7.74860419e-304 7.74860419e-304]


In [55]:
a=np.empty(6,dtype=int)
print(a)

[11 15 20 25 30 35]


In [58]:
      c=np.empty(5,dtype=object)                                                                  # creating an 1-D empty array

In [59]:
print(c)

[None None None None None]


In [61]:
s=np.empty(4,dtype=int)                  # creating an 1-D empty array, with integer datatype
print(s)

[ 1595993607 -1898916789  -584181272  -872522663]


In [62]:
p=np.empty(4, dtype=object)
print(p)
# creating an 1-D empty array, with object datatype

[None None None None]


In [63]:
m=np.empty((3,5))
print(m)
# Creating a 2-D empty array

[[ 2.  4.  6.  8. 10.]
 [12. 14. 16. 18. 20.]
 [22. 24. 26. 28. 30.]]


In [66]:
m=np.empty((3,5),dtype=int)
print(m)

[[      0       0       0       0       0]
 [      0       0       0       0       0]
 [   1368       0       0 7274572       0]]


In [67]:
b=np.empty((5,9), dtype=object)
print(b)

[[None None None None None None None None None]
 [None None None None None None None None None]
 [None None None None None None None None None]
 [None None None None None None None None None]
 [None None None None None None None None None]]


In [70]:
d=np.empty([2,5,3])                                                       # Creating a 3-D empty array
print(d)

[[[1.11099251e-311 1.01777523e-321 0.00000000e+000]
  [0.00000000e+000 1.33511018e-306 1.16097020e-028]
  [1.26087994e-076 2.80061835e-028 6.81211850e-038]
  [1.04917183e-153 5.23081515e-143 1.41599427e-076]
  [3.88589187e-057 1.71796607e+185 3.64054044e+175]]

 [[1.70098498e+256 5.49109388e-143 1.06396443e+224]
  [3.96041428e+246 1.16318408e-028 1.48582052e-076]
  [5.04457326e+174 9.27723476e-072 7.92237060e+165]
  [1.01848862e+248 1.16096643e-028 3.68777431e+180]
  [5.56111702e+180 5.74015544e+180 1.94919988e-153]]]


In [71]:
s=np.empty([2,6,9], dtype=int)                              # Creating a 3-D empty array, with data type integer
print(s)

[[[ 1353548803    31040969  1353548803    31040969         950
             0        4096           0          32]
  [         32           0     5570584     3604558     4259890
       8257588     3014705     5242953     5570649]
  [    7602286     7602281     6619244     3211364     3014709
       7340137     7209081          98         128]
  [          0  -587363030    31042321   670910371    31042322
     670910371    31042322   670910371    31042322]
  [        589           0         592           0          32
            32           0     5570584     4522062]
  [    3145779     8257585     3014705     5242953     5570649
       7602286     7602281     6619244     3211364]]

 [[    3014710     7340137     7209081          98         128
             0  1763484780    31030460 -1028149436]
  [   31033492 -1276465552    31030460 -1276465552    31030460
           589           0         592           0]
  [         32          30           0     5570584     5505102
       5505097 

In [73]:
o=np.empty([2,5,3], dtype=object)                                      # Creating a 3-D empty array, with data type object
print(o)

[[[None None None]
  [None None None]
  [None None None]
  [None None None]
  [None None None]]

 [[None None None]
  [None None None]
  [None None None]
  [None None None]
  [None None None]]]


In [74]:
s=np.empty([2,5,3], dtype=int)
print(s)

[[[         0 1073741824          0]
  [1074790400          0 1075314688]
  [         0 1075838976          0]
  [1076101120          0 1076363264]
  [         0 1076625408          0]]

 [[1076887552          0 1077018624]
  [         0 1077149696          0]
  [1077280768          0 1077411840]
  [         0 1077542912          0]
  [1077673984          0 1077805056]]]


# Eye Function in Python

The Eye function return a 2-D array, with 1 on diagonal and 0 elsewhere

Sytax>  np.eye(shape, k, dtype)

Here: If only number of rows is passed then number of "columns=No. of Rows"

K is index of diagonal, by default, k=0 means main diagonal; when k=+ve means upper diagonal & k=-Ve lower diagonal

The default data type is float

In [77]:
import numpy as np                                        # import numpy libary

In [78]:
a=np.eye(4)                                        # creating an array of shape 4x4
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [85]:
A=np.eye(12, k=0)                                       # creating an array of shape 4x4, with 1 at main diagonal
print(A)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [87]:
B=np.eye(4, k=1)                          # creating an array of shape 4x4, with 1 at upper diagonal
print(B)    

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [89]:
L=np.eye(6, k=-1)                                         # creating an array of shape 4x4, with 1 at lower diagonal
print(L)    

[[0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


In [91]:
i=np.eye(4, dtype=int)                                      # creating an array of shape 4x4, with an integer data type
print(i)
    

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [92]:
E=np.eye(4,5)                              # creating an array of shape 4x5, with an object data type
print(E)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [93]:
a=np.eye(5,4)                                                        # Creating an array with shape of 5x4
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [94]:
np.eye(5,6, k=3, dtype=int)

array([[0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [95]:
np.eye(5, dtype=str)

array([['1', '', '', '', ''],
       ['', '1', '', '', ''],
       ['', '', '1', '', ''],
       ['', '', '', '1', ''],
       ['', '', '', '', '1']], dtype='<U1')

In [96]:
np.ndim(a) # THe array is a two dimensional array

2

# 12. ZEROS LIKE, ONES LIKE, FULL LIKE ARRAY

ZEROS LIKE ARRAY - It returns an array or Zeros, with the same shape & type as of the given array

SYNTAX: np.zeros_like(array,dtype)

In [99]:
import numpy as np                       # Import Numpy library 

In [100]:
   from numpy import random                         # To import random module from numpy library

# ONES LIKE Array-It returns an array of Ones, with the same shape & type as of the given array

SYNTAX: np.ones_like(array,dtype)

In [102]:
a=np.array([21,22,23])                        # Creating an 1-D array.
print(a)

[21 22 23]


In [103]:
b=np.ones_like(a)                                                # creating an ones array, from array A
print(b)

[1 1 1]


In [104]:
c=np.random.random((3,4))                                            # Creating a 2-D Randam array of shape 3x4
print(c)

[[0.67299475 0.07217279 0.73930388 0.67097923]
 [0.55146864 0.85271695 0.69893857 0.51302518]
 [0.51017993 0.43496303 0.11364945 0.81803181]]


In [106]:
d=np.ones_like(c)                                                        # Creating an Ones array from array c
print(d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [107]:
e=np.ones_like(c, dtype=int)          # Creating an ones array of integer data type, from array c
print(e)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


# ZERO'S LIKE ARRAY -Ii returns an array of Zeros, with the same shape & type as of the given array

SYNTAX:: np.zeros_like(array,dtype)

In [108]:
a               # Creating a zeros array, from array A
    

array([21, 22, 23])

In [109]:
b=np.zeros_like(a)       #
print(a)

[21 22 23]


In [114]:
s=np.random.randn(2,5)                            # Creating a 2-D random array of shape 2x5
print(s)    

[[-0.84509781 -0.38313618  0.26305242  0.74206884  1.65507153]
 [ 0.67157358  0.87933624  0.86441895 -0.31472956  0.67816918]]


In [115]:
D=np.zeros_like(c)                                    # Creating a zeros array, from array C
print(D)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [116]:
i=np.zeros_like(c, dtype=int)                                         # creating a zeros array, from array c data type integer
print(i)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


FULL Like Array - It returns a full array of Constant element with the same shape & type of the given array

In [117]:
a                                # Creating a full array of 7, from array A
    

array([21, 22, 23])

In [119]:
b=np.full_like(a,7)
print(b)

[7 7 7]


In [120]:
c=np.random.randn(2,3,5)                                            # Creating a 3-D random array of shape 2x3x4
print(c)

[[[-1.20781873  0.78602967 -0.51565694  0.77073847 -0.87045033]
  [-0.33539373 -1.14289645 -0.85958237  1.05832287 -0.02543919]
  [-0.59588902  0.55898044 -2.22337636  0.3144329   0.38461073]]

 [[-0.52385244 -0.71763123  1.10304555 -0.11300497 -0.06806205]
  [ 0.78103161  0.62637022 -1.10811532  0.06166569  0.04679701]
  [ 0.35725063  0.0234082  -1.08460599  1.46149734 -0.60440574]]]


In [121]:
t=np.full_like(d, 71)                                            # Creating a full array of 71, from array C
print(t)

[[71. 71. 71. 71.]
 [71. 71. 71. 71.]
 [71. 71. 71. 71.]]


In [122]:
E=np.full_like(c, -71, dtype=int)               # Creating a full array of -71, from array C, interger datatype
print(E)

[[[-71 -71 -71 -71 -71]
  [-71 -71 -71 -71 -71]
  [-71 -71 -71 -71 -71]]

 [[-71 -71 -71 -71 -71]
  [-71 -71 -71 -71 -71]
  [-71 -71 -71 -71 -71]]]


# 15. Diagonal Function in Python

It is used to extract the diagonal elements of an array or used to construct a new diagonal array

SYNTAX: np.diag(a,k)

Note:
    It 'a' is a 2-D array, it extract the diagonal elements.
   

 If 'a' is a 1-D array, it construct a 2-D array with element of 'a' on diagonal.
    

By default, k is 0 use k>0 for diagonals above the main diagonal. Use k<0 for diagonals below main diagonal

In [125]:
 import numpy as np                               # to import numpy library
    

In [126]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])                                    # Creating a 2-D array of 3x3
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [127]:
   A.ndim                             # To check the dimensions of an array 'variable'

2

In [129]:
np.diag(A)  # extracting the diagonal element of an array ""

array([1, 5, 9])

In [132]:
B=np.array([1,2,3,4])                                            # Creating an 1-D array
print(B)

[1 2 3 4]


In [133]:
B.ndim                                                # To check the dimension of a "B"

1

In [134]:
np.diag(B)                 # Constructing a 2-D diagonal array with elements of array "B"

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [135]:
np.diag(A, k=0)                                                # when k=0, it will consider the main diagonal

array([1, 5, 9])

In [137]:
np.diag(A, k=2)                                                # when k>0, it will consider the upper diagonal

array([3])

In [138]:
np.diag(A, k=-1)                                                 # when k<0, it will consider the lower diagonal

array([4, 8])

In [140]:
np.diag(B, k=0)                                            # When k=0, element will be at main  diagonal

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [142]:
np.diag(B, k=2)                                                        # when k>0, element will be at upper diagonal

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [143]:
 np.diag(B, k=-5)                                                        # when k<0, element will be at upper diagonal

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0]])

In [144]:
x=np.random.randn(2,3,4)                                        # a 3-D random array of shape 2x3x4
print(x)

[[[-0.78484724 -0.51938515 -0.0636538   0.78720242]
  [-0.41760246 -0.83016184 -0.84497078 -0.09720181]
  [ 0.34196161 -1.16127175  1.30493171  0.75137772]]

 [[-0.03493324  0.00671907 -0.56996689 -1.08344215]
  [-0.12943191 -0.20500946 -0.49176289 -0.89950086]
  [-1.63555945  0.46484248  0.9221078  -2.48880376]]]


# 16.v-39== TRANSPOSE FUNCTION IN PYTHON

IT CONVERTS THE ROWS INTO COLUMNS, AND COLUMN INTO ROWS

SYNTAX:: array.T or
        np.transpose(array)

In [151]:
A=np.array([[2,3,4], [7,8,9]])                                               # To import numpy library
print(A)

[[2 3 4]
 [7 8 9]]


In [152]:
A.T                                                # creating a 2-D array of 2x3

array([[2, 7],
       [3, 8],
       [4, 9]])

In [153]:
A.shape                                                # Transpose of an array of 'A'

(2, 3)

In [154]:
A.T.shape                                                # Chekcing the original shape of "A"

(3, 2)

In [155]:
np.transpose(A)                                                # Checking the shape of A, after the transpose

array([[2, 7],
       [3, 8],
       [4, 9]])

In [156]:
                                                # alternate command to transpose

# TRANSPOSE OF 1-D ARRAY

In [161]:
B=np.array([10,9,8,7,6,5])                                                        # CREATING A 1-D ARRAY of 6 elements
print(B)

[10  9  8  7  6  5]


In [162]:
B.T                                                        # Transpose of array B

array([10,  9,  8,  7,  6,  5])

In [163]:
B.shape                                                        # Checking the original shape of B
    

(6,)

In [164]:
B.T.shape                                                      # Chekcing the shape of B, after the  transpose

(6,)

# TRANSPOSE OF A 3-D ARRAY

In [168]:
C=np.array([[5,6,7],[1,2,3],[7,8,9]])                                        # Creating a 3-D array of 1x3x3 element
print(C)

[[5 6 7]
 [1 2 3]
 [7 8 9]]


In [169]:
  C.T                                      # Transpose of array C

array([[5, 1, 7],
       [6, 2, 8],
       [7, 3, 9]])

In [171]:
C.shape                                        # Checking the original shape of C

(3, 3)

In [172]:
C.T.shape                                        # Checking the original shape of C, after the transpose

(3, 3)

# 40. UNARY OPERATORS -- Those operators that require only one operand

These function can be applied row-wise or column-wise by setting an 'axis' parameter

In [173]:
import numpy as np

In [174]:
A=np.array([23,24,25,26,29])
print(A)

[23 24 25 26 29]


In [175]:
A.max()

29

In [176]:
A.min()

23

In [177]:
A.sum()

127

In [181]:
B=np.array([[48,48,50],[79,89,99]])
print(B)

[[48 48 50]
 [79 89 99]]


In [182]:
B.max()

99

In [183]:
B.max(axis=1)

array([50, 99])

In [184]:
B.min(axis=0)

array([48, 48, 50])

In [185]:
B.min()

48

In [186]:
B.min(axis=1)

array([48, 79])

In [187]:
B.min(axis=0)

array([48, 48, 50])

In [188]:
B.sum()

413

In [189]:
B.sum(axis=1)

array([146, 267])

In [190]:
B.sum(axis=0)

array([127, 137, 149])

In [195]:
c=np.arange(127).reshape(12,13,23)

ValueError: cannot reshape array of size 127 into shape (12,13,23)

In [194]:
print(c)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126]


In [196]:
C.max()

9

In [197]:
C.mean()

5.333333333333333

In [198]:
C.min()

1

In [199]:
C.min(axis=1)

array([5, 1, 7])

In [200]:
C.min(axis=0)

array([1, 2, 3])

In [201]:
C.max(axis=0)

array([7, 8, 9])

In [202]:
C.max(axis=1)

array([7, 3, 9])

In [203]:
C.sum()

48

In [204]:
C.sum(axis=1)

array([18,  6, 24])

In [205]:
C.sum(axis=0)

array([13, 16, 19])

# 41. Vstack and Hstack

VERTICAL AND HORIZONTAL

VSTACK AND HSTACK is used to combine two or more arrays to form a new array

VSTACK- Combines the arrays vertically

HSTACK-Combines the arrays Horizontally

In [1]:
import numpy as np

# In 1-D Array

In [3]:
A=np.array([1,2,3,4,5])


In [4]:
B=np.array([11,22,33,44,55])

In [5]:
np.vstack((A,B))

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [6]:
np.hstack((A,B))

array([ 1,  2,  3,  4,  5, 11, 22, 33, 44, 55])

# IN 2-D ARRAY

In [8]:
P=([[3,4,5,6],[8,9,7,6]])
P

[[3, 4, 5, 6], [8, 9, 7, 6]]

In [9]:
Q=([[11,12,13,14],[10,20,30,40]])
Q

[[11, 12, 13, 14], [10, 20, 30, 40]]

In [11]:
V2=np.vstack((P,Q))
V2

array([[ 3,  4,  5,  6],
       [ 8,  9,  7,  6],
       [11, 12, 13, 14],
       [10, 20, 30, 40]])

In [12]:
V3=np.hstack((P,Q))
V3

array([[ 3,  4,  5,  6, 11, 12, 13, 14],
       [ 8,  9,  7,  6, 10, 20, 30, 40]])

# IN 3-D ARRAY

In [13]:
N=([[2,3,4],[4,5,6],[8,9,10]])
N

[[2, 3, 4], [4, 5, 6], [8, 9, 10]]

In [14]:
M=([[11,12,13],[7,8,9],[5,6,7]])
M

[[11, 12, 13], [7, 8, 9], [5, 6, 7]]

In [16]:
S=np.vstack((N,M))
S

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [11, 12, 13],
       [ 7,  8,  9],
       [ 5,  6,  7]])

In [17]:
S1=np.hstack((N,M))
S1

array([[ 2,  3,  4, 11, 12, 13],
       [ 4,  5,  6,  7,  8,  9],
       [ 8,  9, 10,  5,  6,  7]])

In [18]:
S.shape

(6, 3)

In [19]:
S1.shape

(3, 6)

# NUMPY ARRAY INDEXING

Indexing is used to obtain particular element(s) or row(s) or coloumn(s) from the numpy array(s)